# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'FirebaseAuth', '11.5.0'
  pod 'FirebaseFirestore', '11.5.0'
  pod 'FirebaseCrashlytics', '11.5.0'
  pod 'FirebaseAnalytics', '11.5.0'
  # Temporarily disabled Google Sign-In due to framework conflicts
  # pod 'GoogleSignIn', '~> 7.1'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end

