package com.brainburst.domain.game.sudoku

import kotlinx.serialization.Serializable

/**
 * Payload for 6x6 Mini Sudoku puzzles
 * This is the format stored in Firestore and generated by GPT
 */
@Serializable
data class Sudoku6x6Payload(
    val size: Int = 6,
    val blockRows: Int = 2,
    val blockCols: Int = 3,
    val initialBoard: List<List<Int>>,  // 6x6 grid with 0 for empty, 1-6 for givens
    val solutionBoard: List<List<Int>>  // 6x6 grid with complete solution (1-6)
) {
    init {
        require(size == 6) { "Sudoku size must be 6" }
        require(blockRows * blockCols == 6) { "blockRows * blockCols must equal 6" }
        require(initialBoard.size == 6) { "initialBoard must have 6 rows" }
        require(initialBoard.all { it.size == 6 }) { "initialBoard must have 6 columns" }
        require(solutionBoard.size == 6) { "solutionBoard must have 6 rows" }
        require(solutionBoard.all { it.size == 6 }) { "solutionBoard must have 6 columns" }
    }
}

