package com.brainburst.domain.game.tango

import kotlinx.serialization.Serializable

/**
 * Payload for Tango puzzles
 * This is the format stored in Firestore and generated by the backend
 */
@Serializable
data class TangoPayload(
    val size: Int = 6,  // Fixed 6x6 grid
    val prefilled: List<PrefilledCell> = emptyList(),  // Pre-filled cells
    val equalClues: List<EqualClue> = emptyList(),  // Adjacent cells must match
    val oppositeClues: List<OppositeClue> = emptyList()  // Adjacent cells must be opposite
) {
    init {
        require(size == 6) { "Tango grid size must be 6" }
        require(prefilled.all { it.row in 0 until size && it.col in 0 until size }) {
            "All prefilled cells must be within grid bounds"
        }
    }
}

/**
 * Represents a pre-filled cell in the puzzle
 */
@Serializable
data class PrefilledCell(
    val row: Int,
    val col: Int,
    val value: CellValue  // SUN or MOON
)

/**
 * Represents an "=" clue between two adjacent cells (must match)
 */
@Serializable
data class EqualClue(
    val row: Int,
    val col: Int,
    val direction: ClueDirection  // HORIZONTAL or VERTICAL
)

/**
 * Represents an "×" clue between two adjacent cells (must be opposite)
 */
@Serializable
data class OppositeClue(
    val row: Int,
    val col: Int,
    val direction: ClueDirection  // HORIZONTAL or VERTICAL
)

/**
 * Direction of a clue (which adjacent cell it points to)
 */
@Serializable
enum class ClueDirection {
    HORIZONTAL,  // Clue points to the cell on the right
    VERTICAL     // Clue points to the cell below
}

/**
 * Cell values in Tango
 */
@Serializable
enum class CellValue {
    EMPTY,
    SUN,
    MOON
}
