package com.brainburst.domain.game.zip

import com.brainburst.domain.game.Position
import kotlinx.serialization.Serializable

/**
 * Payload for ZIP puzzles
 * This is the format stored in Firestore and generated by GPT
 */
@Serializable
data class ZipPayload(
    val size: Int = 6,  // Fixed 6x6 grid
    val dots: List<ZipDot>,  // Numbered dots to connect (1 to N)
    val walls: List<ZipWall> = emptyList()  // Wall barriers that block paths
) {
    init {
        require(size == 6) { "ZIP grid size must be 6" }
        require(dots.size >= 2) { "ZIP must have at least 2 dots" }
        require(dots.size <= 16) { "ZIP must have at most 16 dots" }
        require(dots.all { it.row in 0 until size && it.col in 0 until size }) {
            "All dots must be within grid bounds"
        }
        require(dots.mapIndexed { idx, dot -> dot.index == idx + 1 }.all { it }) {
            "Dots must be numbered sequentially starting from 1"
        }
    }
    
    /**
     * Get the total number of dots
     */
    val dotCount: Int get() = dots.size
    
    /**
     * Find a dot by its index (1 to N)
     */
    fun getDot(index: Int): ZipDot? = dots.find { it.index == index }
    
    /**
     * Get the position of a specific dot
     */
    fun getDotPosition(index: Int): Position? = getDot(index)?.toPosition()
}

/**
 * Represents a numbered dot in the ZIP puzzle
 */
@Serializable
data class ZipDot(
    val row: Int,
    val col: Int,
    val index: Int  // 1 to N
) {
    fun toPosition(): Position = Position(row, col)
}

/**
 * Represents a wall barrier on a cell edge
 * Walls prevent paths from crossing between adjacent cells
 */
@Serializable
data class ZipWall(
    val row: Int,
    val col: Int,
    val side: WallSide  // Which edge of the cell has the wall
)

@Serializable
enum class WallSide {
    TOP,    // Wall on top edge (blocks movement to row-1)
    RIGHT,  // Wall on right edge (blocks movement to col+1)
    BOTTOM, // Wall on bottom edge (blocks movement to row+1)
    LEFT    // Wall on left edge (blocks movement to col-1)
}
